"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GenerateRssFeedConfig = exports.ConvertToRssConfig = exports.SanitizationConfig = exports.ConvertToSpasmConfig = exports.IgnoreWhitelistFor = void 0;
const utils_js_1 = require("./../utils/utils.js");
class IgnoreWhitelistFor {
    action;
    constructor() {
        this.action = {
            post: false,
            reply: false,
            react: false,
            moderate: false
        };
    }
}
exports.IgnoreWhitelistFor = IgnoreWhitelistFor;
class ConvertToSpasmConfig {
    to;
    from;
    signature;
    xss;
    constructor() {
        this.to = {
            spasm: {
                version: "2.0.0",
                type: "SpasmEventV2",
                id: {
                    versions: ["01"]
                }
            }
        };
        this.from = {
            spasm: { enableEventVerification: true },
            dmp: { enableEventVerification: true },
            nostr: { enableEventVerification: true }
        };
        this.signature = {
            ethereum: { enableVerification: true },
            nostr: { enableVerification: true }
        };
        this.xss = {
            enableSanitization: true,
            sanitizationConfig: new SanitizationConfig()
        };
        this.xss.sanitizationConfig = new SanitizationConfig();
    }
}
exports.ConvertToSpasmConfig = ConvertToSpasmConfig;
class SanitizationConfig {
    customFunction;
    valueType;
    maxDepth;
    constructor() {
        this.customFunction = utils_js_1.sanitizeStringWithDompurify,
            this.valueType = "string",
            this.maxDepth = 100;
    }
}
exports.SanitizationConfig = SanitizationConfig;
class ConvertToRssConfig {
    to;
    customDomain;
    customGuid;
    customLink;
    addSpasmEnvelope;
    extraContent;
    constructor() {
        this.to = {
            rss: {
                type: "RssEvent",
            }
        };
        this.addSpasmEnvelope = true;
        this.extraContent = {
            forAction: {
                post: { enabled: false },
                reply: { enabled: true },
                react: { enabled: true }
            },
            addDomain: { enabled: true },
            text: "\n\n---\nThis is a response to: "
        };
    }
}
exports.ConvertToRssConfig = ConvertToRssConfig;
class GenerateRssFeedConfig {
    channel;
    items;
    customConvertToRssConfig;
    constructor() {
        this.channel = {
            title: "Spasm RSS",
            description: "RSS Feed of Spasm events",
            language: "en-us",
            lastBuildDate: new Date().toUTCString()
        };
        this.items = {
            enableAutoGeneratedNames: true
        };
    }
}
exports.GenerateRssFeedConfig = GenerateRssFeedConfig;
// Ideas:
// - Short names? SE2 SE2Body SE2Envelope SE2EnvelopeWithTree
//# sourceMappingURL=interfaces.js.map