"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConvertToSpasmSimpleConfig = exports.GenerateRssFeedConfig = exports.ConvertToRssConfig = exports.RssFeed = exports.SanitizationConfig = exports.ConvertToSpasmConfig = exports.IgnoreWhitelistFor = void 0;
const utils_js_1 = require("./../utils/utils.js");
class IgnoreWhitelistFor {
    action;
    constructor() {
        this.action = {
            post: false,
            reply: false,
            react: false,
            moderate: false
        };
    }
}
exports.IgnoreWhitelistFor = IgnoreWhitelistFor;
class ConvertToSpasmConfig {
    to;
    from;
    signature;
    xss;
    constructor() {
        this.to = {
            spasm: {
                version: "2.0.0",
                type: "SpasmEventV2",
                id: {
                    versions: ["01"]
                }
            }
        };
        this.from = {
            spasm: { enableEventVerification: true },
            dmp: { enableEventVerification: true },
            nostr: { enableEventVerification: true }
        };
        this.signature = {
            ethereum: { enableVerification: true },
            nostr: { enableVerification: true }
        };
        this.xss = {
            enableSanitization: true,
            sanitizationConfig: new SanitizationConfig()
        };
        this.xss.sanitizationConfig = new SanitizationConfig();
    }
}
exports.ConvertToSpasmConfig = ConvertToSpasmConfig;
class SanitizationConfig {
    customFunction;
    valueType;
    maxDepth;
    constructor() {
        this.customFunction = utils_js_1.sanitizeStringWithDompurify,
            this.valueType = "string",
            this.maxDepth = 100;
    }
}
exports.SanitizationConfig = SanitizationConfig;
// Parsed RSS feed (or Atom)
class RssFeed {
    title;
    description;
    link;
    feedUrl;
    lastBuildDate;
    updated;
    author;
    isoDate;
    language;
    image;
    paginationLinks;
    items;
    item;
    entry;
}
exports.RssFeed = RssFeed;
class ConvertToRssConfig {
    to;
    customDomain;
    customGuid;
    customLink;
    addSpasmEnvelope;
    extraEventInfo;
    extraContent;
    convertDescriptionToHtml;
    postExecutionHook;
    constructor() {
        this.to = {
            rss: {
                type: "RssEvent",
            }
        };
        this.addSpasmEnvelope = true;
        this.extraEventInfo = {
            forAction: {
                post: { enabled: true },
                reply: { enabled: true },
                react: { enabled: true }
            },
            addSubmitComment: { enabled: true },
            addSignedDate: { enabled: true },
            addSigner: { enabled: true },
        };
        this.extraContent = {
            forAction: {
                post: { enabled: false },
                reply: { enabled: true },
                react: { enabled: true }
            },
            addDomain: { enabled: true },
            text: "\n\n---\nThis message is a response to: "
        };
        this.convertDescriptionToHtml = true;
    }
}
exports.ConvertToRssConfig = ConvertToRssConfig;
class GenerateRssFeedConfig {
    channel;
    items;
    filters;
    customConvertToRssConfig;
    constructor() {
        this.channel = {
            title: "Spasm",
            description: "RSS Feed of Spasm events",
            language: "en-us",
            lastBuildDate: new Date().toUTCString(),
            imageUrl: "https://media.spasm.network/spasmim016863a1cae922c77a970a86e0d339455d6417c6106125b8ebac744e50f51581a9.jpeg",
            addSignerToTitle: true,
            enableAutoGeneratedNamesInTitle: true
        };
        this.items = {
            enableAutoGeneratedNames: true
        };
    }
}
exports.GenerateRssFeedConfig = GenerateRssFeedConfig;
class ConvertToSpasmSimpleConfig {
    version;
    limit;
    constructor() {
        this.version = "2.0.0";
        this.limit = {
            title: 256,
            content: 2048,
            timestamp: 30,
            author: 256,
            action: 256,
            parentId: 256,
            categories: 256,
            source: 256,
            ids: 256
        };
    }
}
exports.ConvertToSpasmSimpleConfig = ConvertToSpasmSimpleConfig;
// Ideas:
// - Short names? SE2 SE2Body SE2Envelope SE2EnvelopeWithTree
//# sourceMappingURL=interfaces.js.map